#!/bin/bash
cd "/Users/haimdayan/Desktop/FixOnce"
/Library/Frameworks/Python.framework/Versions/3.13/Resources/Python.app/Contents/MacOS/Python "/Users/haimdayan/Desktop/FixOnce/scripts/app_launcher.py" &
sleep 1
osascript -e 'tell application "System Events" to set frontmost of process "Python" to true'
